// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCLBackend.Service;

namespace UCLBackend.Service.Migrations
{
    [DbContext(typeof(UCLContext))]
    partial class UCLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("UCLBackend.Service.Account", b =>
                {
                    b.Property<string>("UCLID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountID")
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.HasKey("UCLID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("UCLBackend.Service.User", b =>
                {
                    b.Property<string>("UCLID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiscordID")
                        .HasColumnType("longtext");

                    b.Property<string>("League")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PeakMMR")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("double");

                    b.Property<string>("System")
                        .HasColumnType("longtext");

                    b.Property<string>("Team")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeZone")
                        .HasColumnType("longtext");

                    b.HasKey("UCLID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
